#use_frameworks!
use_modular_headers!
platform :ios, '10.0'

target 'ZYFComponentTool_Example' do
  pod 'ZYFComponentTool', :path => '../'

  target 'ZYFComponentTool_Tests' do
    inherit! :search_paths

    
  end
end
